apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fieldglass-cron.fullname" . }}-secret
  labels:
    {{- include "fieldglass-cron.labels" . | nindent 4 }}
type: Opaque
stringData:
  CRON_SECRET: {{ .Values.cronjob.cronSecret | quote }}